### ISSUE TITLE
Final version/release please

### ISSUE THREAD

**Issue by sreichel** [Vinai/attribute-duplicator#1]
Hello,

we still use it and I would like to get the latest version when installing with composer. Please do a last version bump.

Regards

**Comment by Vinai** [comment]
Will do when I get home tomorrow!
That said, would you be willing to adopt the extension?

**Comment by sreichel** [comment]
Thank you. 

As long i have to work with M1 i've not problem to maintain it. Seem to be quite here :)

**Comment by Vinai** [comment]
I've pushed the tag 1.0.0

It is indeed very quite here. The only change you would need to make maybe is remove the note from the readme that the module is orphaned.

**Comment by Vinai** [comment]
I've requested a transfer of the repository to @sreichel

**Comment by Vinai** [comment]
Hm, that didn't work - you already have a repository with that name ^^

Maybe I'll just add you as a collaborator with all permissions for now.

**Comment by sreichel** [comment]
Yes, forked it years ago :)

"collaborator" with some rights should be enough. Thank you.

I'll update readme later and maybe add a "fix" that notice uses if the attribute uses customer source/backend/... models.
